# Generated by Django 5.2.8 on 2025-12-12 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attending', models.BooleanField(default=False)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
