# Generated by Django 5.2.8 on 2025-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guestgroup',
            name='guest_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
